@port=4400
###@url=https://sea-lion-app-ovmmi.ondigitalocean.app
@url=http://localhost

###
GET {{url}}:{{port}}/greetings 

### local
GET http://localhost:{{port}}/products 

### PROD
GET https://sea-lion-app-ovmmi.ondigitalocean.app/products

###
GET http://localhost:{{port}}/contact

###
POST http://localhost:{{port}}/send
Content-Type: application/json

{
    "greetings": "George Clooney"
}

###
GET http://localhost:{{port}}

###
POST http://localhost:{{port}}/addnewproduct
Content-Type: application/json

{
    "name": "NEW IPHONE",
    "price": 999
}

###
PUT http://localhost:{{port}}/updateproduct
Content-Type: application/json

{
    "id": 1,
    "price": 100000
}
